// Angular/connecting-to-database/syncfusion-angular-diagram-MySQL/diagram_mysql.client/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import {
  DiagramComponent, DiagramModule, DataBindingService,
  HierarchicalTreeService, LayoutModel, DataSourceModel, NodeModel,
  SnapSettingsModel,
  SnapConstraints
} from '@syncfusion/ej2-angular-diagrams';
import { DataManager } from '@syncfusion/ej2-data';

export interface Employee { id: number; name: string; parentId?: number | null; }

const BASE_URL = 'http://localhost:5296/api/diagram/items';

@Component({
  selector: 'app-root',
  imports: [DiagramModule],
  providers: [DataBindingService, HierarchicalTreeService],
  templateUrl: './app.html',
})
export class App implements OnInit {
  public layout: LayoutModel = {
    type: 'OrganizationalChart',
  }
  public dataSourceSettings?: DataSourceModel;

  ngOnInit(): void {
    const items = new DataManager({ url: BASE_URL });
    this.dataSourceSettings = {
      id: 'id',
      parentId: 'parentId',
      dataSource: items,
      doBinding: (nodeModel: NodeModel, data: Employee) => {
        nodeModel.annotations = [{
          content: data.name,
          style: { color: '#FFFFFF' }
        }];
      }
    };
  }

  public getNodeDefaults(obj: NodeModel): NodeModel {
    obj.width = 120;
    obj.height = 40;
    obj.style = { fill: '#1F3A8A', strokeColor: '#1E40AF' };
    return obj;
  };

  public getConnectorDefaults(connector: any): void {
    connector.type = 'Orthogonal';
    connector.cornerRadius = 7;
    connector.targetDecorator = { shape: 'None' };
    connector.style = {
      strokeColor: '#94A3B8',
      strokeWidth: 1.5
    };
  };

  public snapSettings: SnapSettingsModel = { constraints: SnapConstraints.None }
}

// React/connecting-to-database/syncfusion-react-diagram-MySQL/diagram_mysql.client/src/App.tsx
import React from "react";
import {
  DiagramComponent,
  Inject,
  DataBinding,
  HierarchicalTree,
  type NodeModel,
  type ConnectorModel,
  SnapConstraints,
} from "@syncfusion/ej2-react-diagrams";
import { DataManager } from "@syncfusion/ej2-data";

export interface Employee { id: number; name: string; parentId?: number | null; }

export default function App() {
  const dataManager = new DataManager({
    url: "http://localhost:5283/api/diagram/items",
  });

  return (
    <div>
      <DiagramComponent
        id="diagram"
        width={"100%"}
        height={"600px"}
        snapSettings={{ constraints: SnapConstraints.None }}
        // Use hierarchical tree layout
        layout={{ type: "HierarchicalTree" }}
        // Configure data source mapping
        dataSourceSettings={{
          id: "id",
          parentId: "parentId",
          dataSource: dataManager,
          doBinding: (nodeModel: NodeModel, data: Employee) => {
            nodeModel.annotations = [{
              content: data.name,
              style: { color: '#FFFFFF' }
            }];
          }
          // nameField for node label mapping
          // if the component uses node data name, use 'Name' in getNodeDefaults below
        }}
        getNodeDefaults={(node: NodeModel) => {
          node.width = 120;
          node.height = 40;
          node.style = { fill: '#1F3A8A', strokeColor: '#1E40AF' };
          return node;
        }}
        getConnectorDefaults={(connector: ConnectorModel) => {
          connector.type = 'Orthogonal';
          connector.cornerRadius = 7;
          connector.targetDecorator = { shape: 'None' };
          connector.style = {
            strokeColor: '#94A3B8',
            strokeWidth: 1.5
          };
        }}
      >
        <Inject services={[DataBinding, HierarchicalTree]} />
      </DiagramComponent>
    </div>
  );
}
