// Vue/connecting-to-database/syncfusion-vue-diagram-MSSQL/Vue_Diagram_MSSQL.client/src/App.vue
<template>
  <div>
    <ejs-diagram
      id="diagram"
      :width="'1000px'"
      height="600px"
      :snapSettings="{ constraints: SnapConstraints.None }"
      :layout="{ type: 'HierarchicalTree' }"
      :dataSourceSettings="dataSourceSettings"
      :getNodeDefaults="getNodeDefaults"
      :getConnectorDefaults="getConnectorDefaults"
    >
    </ejs-diagram>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { DataManager } from "@syncfusion/ej2-data";
import { DiagramComponent, DataBinding, HierarchicalTree, SnapConstraints } from "@syncfusion/ej2-vue-diagrams";

export default defineComponent({
  name: "App",
  components: {
    'ejs-diagram': DiagramComponent
  },
  provide: {
     diagram: [DataBinding, HierarchicalTree]
  },
  data() {
    const dataManager = new DataManager({
      url: "http://localhost:5137/api/Diagram",
    });

    return {
      dataManager,
      DataBinding,
      HierarchicalTree,
      SnapConstraints,
      dataSourceSettings: {
        id: "id",
        parentId: "parentId",
        dataSource: dataManager,
        doBinding: (nodeModel: any, data: any) => {
          nodeModel.annotations = [
            {
              content: data.name,
              style: { color: "#FFFFFF" },
            },
          ];
        },
      },
    };
  },
  methods: {
    getNodeDefaults(node: any) {
      node.width = 120;
      node.height = 40;
      node.style = { fill: "#1F3A8A", strokeColor: "#1E40AF" };
      return node;
    },
    getConnectorDefaults(connector: any) {
      connector.type = "Orthogonal";
      connector.cornerRadius = 7;
      connector.targetDecorator = { shape: "None" };
      connector.style = { strokeColor: "#94A3B8", strokeWidth: 1.5 };
      return connector;
    },
  },
});

</script>

<style>
  @import "../node_modules/@syncfusion/ej2-base/styles/material.css";
  @import "../node_modules/@syncfusion/ej2-popups/styles/material.css";
  @import "../node_modules/@syncfusion/ej2-splitbuttons/styles/material.css";
  @import "../node_modules/@syncfusion/ej2-navigations/styles/material.css";
  @import "../node_modules/@syncfusion/ej2-diagrams/styles/material.css";
</style>

// React/connecting-to-database/syncfusion-react-diagram-MySQL/diagram_mysql.client/src/App.tsx
import React from "react";
import {
  DiagramComponent,
  Inject,
  DataBinding,
  HierarchicalTree,
  type NodeModel,
  type ConnectorModel,
  SnapConstraints,
} from "@syncfusion/ej2-react-diagrams";
import { DataManager } from "@syncfusion/ej2-data";

export interface Employee { id: number; name: string; parentId?: number | null; }

export default function App() {
  const dataManager = new DataManager({
    url: "http://localhost:5283/api/diagram/items",
  });

  return (
    <div>
      <DiagramComponent
        id="diagram"
        width={"100%"}
        height={"600px"}
        snapSettings={{ constraints: SnapConstraints.None }}
        // Use hierarchical tree layout
        layout={{ type: "HierarchicalTree" }}
        // Configure data source mapping
        dataSourceSettings={{
          id: "id",
          parentId: "parentId",
          dataSource: dataManager,
          doBinding: (nodeModel: NodeModel, data: Employee) => {
            nodeModel.annotations = [{
              content: data.name,
              style: { color: '#FFFFFF' }
            }];
          }
          // nameField for node label mapping
          // if the component uses node data name, use 'Name' in getNodeDefaults below
        }}
        getNodeDefaults={(node: NodeModel) => {
          node.width = 120;
          node.height = 40;
          node.style = { fill: '#1F3A8A', strokeColor: '#1E40AF' };
          return node;
        }}
        getConnectorDefaults={(connector: ConnectorModel) => {
          connector.type = 'Orthogonal';
          connector.cornerRadius = 7;
          connector.targetDecorator = { shape: 'None' };
          connector.style = {
            strokeColor: '#94A3B8',
            strokeWidth: 1.5
          };
        }}
      >
        <Inject services={[DataBinding, HierarchicalTree]} />
      </DiagramComponent>
    </div>
  );
}
