// React-Sample/src/App.js
import './App.css';
import * as React from "react";
import { DiagramComponent, SelectorConstraints } from "@syncfusion/ej2-react-diagrams";
function nodeTemplate1(props) {
     return <div><input type="button" id="button" value={props.id}/></div>
}
function nodeTemplate2(props) {
     return <div><input type="button" id="button" value="second"/></div>
}
function annotationTemplate1(props) {
     return <div><input type="button" id="button" value={props.id}/></div>
}
function annotationTemplate2(props) {
     return <div><input type="button" id="button" value="annotation template"/></div>
}
function userHandleTemplate(props) {
     return <div><input type="button" id="button" value="userHandle template"/></div>
}

function App() {
  const nodes = [
    {
      id: 'html1', width: 100, height: 100, offsetX: 100, offsetY: 100,
      shape: { type: 'HTML' }
  },
  {
      id: 'html2', width: 100, height: 100, offsetX: 100, offsetY: 300,
      shape: { type: 'HTML', content: nodeTemplate2 }
  },
  {
      id: 'basic1', width: 100, height: 100, offsetX: 300, offsetY: 100,
      annotations: [{ id:'an1' }],
  },
  {
      id: 'basic2', width: 100, height: 100, offsetX: 300, offsetY: 300,
      annotations: [{ id:'an2', template: annotationTemplate2}],
  }
];
const connectors = [
  { id: 'connector1', sourceID: 'basic1', targetID: 'basic2',annotations: [{ id:'con_an1',template:annotationTemplate1 }] },

]
return (<DiagramComponent id="container"
 width={"100%"}
 height={"700px"}
 nodes={nodes}
 connectors={connectors}
 nodeTemplate={nodeTemplate1.bind(this)}
 annotationTemplate={annotationTemplate1.bind(this)}
 userHandleTemplate={userHandleTemplate.bind(this)}
 selectedItems={{constraints:SelectorConstraints.All| SelectorConstraints.UserHandle,userHandles:[{}]}}
 />);
}

export default App;

// Angular-Sample/my-diagram/src/app/app.component.ts
import { Component, ViewEncapsulation, ViewChild } from '@angular/core';
import { SelectorConstraints, SelectorModel } from '@syncfusion/ej2-angular-diagrams';
import {
  Diagram, NodeModel, UndoRedo, ConnectorModel,
} from '@syncfusion/ej2-diagrams';
Diagram.Inject(UndoRedo);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {
  @ViewChild('diagram')
  //Diagram Properties
  public diagram: any;
  constructor() {​​​​​​​
    
}


public nodes: NodeModel[] = [
  {
    id: 'html1', width: 100, height: 100, offsetX: 100, offsetY: 100,
    shape: { type: 'HTML' }
},
{
    id: 'html2', width: 100, height: 100, offsetX: 100, offsetY: 300,
    shape: { type: 'HTML', }
},
{
    id: 'basic1', width: 100, height: 100, offsetX: 300, offsetY: 100,
    annotations: [{ id:'an1' }],
},
];
public selectedItems: SelectorModel = { 
 constraints: SelectorConstraints.All | SelectorConstraints.UserHandle, userHandles:[{}] 
};
public connectors: ConnectorModel[] = [
  { id: 'connector1', sourceID: 'html2', targetID: 'basic1',annotations: [{ id:'con_an1'}] },

];
}
<link href="https://cdn.syncfusion.com/ej2/material.css" rel="stylesheet" />
<link href="https://cdn.syncfusion.com/ej2/ej2-base/styles/material.css" rel="stylesheet" />
<link href="https://cdn.syncfusion.com/ej2/ej2-buttons/styles/material.css" rel="stylesheet" />
<link href="https://cdn.syncfusion.com/ej2/ej2-popups/styles/material.css" rel="stylesheet" />
<link href="https://cdn.syncfusion.com/ej2/ej2-splitbuttons/styles/material.css" rel="stylesheet" />
<link href="https://cdn.syncfusion.com/ej2/ej2-diagrams/styles/material.css" rel="stylesheet" />
<link href="https://cdn.syncfusion.com/ej2/ej2-navigations/styles/fabric.css" rel="stylesheet" />
  <div style="margin-top: 50px;">
<ejs-diagram #diagram
id="diagram"
width="100%"
height="700px"
[nodes]="nodes"
[connectors]="connectors"
[selectedItems]="selectedItems"
>
  <ng-template #nodeTemplate let-data >
    <ng-container>
        <div style="background-color: aqua;width: 100px;height: 100px;"><input type = "button" value= "node-temp" ></div>
    </ng-container>
  </ng-template>
  <ng-template #annotationTemplate let-data >
    <ng-container>
        <input type = "button" value= "annot-temp" />
    </ng-container>
  </ng-template>
  <ng-template #userHandleTemplate let-data >
    <ng-container>
        <div style="background-color: yellowgreen;height: 30px;"><input type = "checkbox" checked ></div>
    </ng-container>
  </ng-template>
</ejs-diagram>
</div>
